### Get all personnes from database
GET http://localhost:8080/personne/allp
Content-Type: application/json
#### Add personne to database
POST http://localhost:8080/personne/addp
Content-Type: application/json

{
    "nom": "Mohamed",
    "prenom": "Dabebi",
    "cin": "09618107",
    "role":"RESPONSABLE",
    "numtel":"92652461"
}